spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-peer-1:8800/eureka/,http://eureka-peer-2:8800/eureka/

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042
  username:
  password:
