spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

health:
  config:
    enabled: false

management:
  actuator-security:
    username: actuator
    password-hash: "{bcrypt}"

  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full

